name: "Terraform & Docker Deploy to GCP"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/1047664134161/locations/global/workloadIdentityPools/github-pool-v2/providers/github-provider'
          service_account: 'github-actions-sa@bigquery-s3-cloudrun.iam.gserviceaccount.com'

      # 1. Terraform実行（最初は安全なダミーイメージでCloud Runの箱を作る）
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="project_id=bigquery-s3-cloudrun" \
            -var="region=asia-northeast1" \
            -var='allowed_user_email=["suzushika.yuki3@gmail.com", "iucidium.phosphorus@gmail.com"]'

      # 2. リポジトリができたのでDockerビルド・プッシュを行う
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

      - name: Build and Push Docker Container
        run: |
          IMAGE_BASE="asia-northeast1-docker.pkg.dev/bigquery-s3-cloudrun/cloudrun-repo/my-web-app"
          docker build -t $IMAGE_BASE:${{ github.sha }} -t $IMAGE_BASE:latest .
          docker push --all-tags $IMAGE_BASE

      # 3. 最後に自作イメージでCloud Runのリビジョンを最新化する
      - name: Deploy to Cloud Run
        run: |
          gcloud run services update corporate-web-service \
            --image=asia-northeast1-docker.pkg.dev/bigquery-s3-cloudrun/cloudrun-repo/my-web-app:${{ github.sha }} \
            --region=asia-northeast1
